package com.example.projectcheva

object Screens {
    val Splash = Screen("splash")
    val Login = Screen("login")
    val Register = Screen("register")
    val ChangePassword = Screen("change_password")
    val ForgotPassword = Screen("forgot_password")
    val Beranda = Screen("beranda")
    val Favorit = Screen("favorit")
    val Berita = Screen("berita")
    val DetailBerita = Screen("detail_berita")
    val ListBerita = Screen("list_berita")
    val Artikel = Screen("artikel")
    val Budaya = Screen("budaya")
    val DetailBudaya = Screen("detail_budaya")
    val DetailEvent = Screen("detail_event")
    val Profile = Screen("profile")
    val EditProfile = Screen("edit_profile")
    val Loading = Screen("loading")
    val Plan = Screen("plan")
    val LoggedProfile = Screen("logged_user")
    val NotLoggedPage = Screen("not_logged_user")
    val facebook = Screen("facebook")
    val MapScreens = Screen("map?initialPlace={initialPlace}&destinationPlace={destinationPlace}")
    val recomend = Screen("Rekomendasi")
    data class Screen(val route: String)
}
